# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Build (fabric) with Gradle
      run: ./gradlew build -Pbaritone.fabric_build

    - name: Build (forge) with Gradle
      run: ./gradlew build -Pbaritone.forge_build -Ploom.platform=forge

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: dist/
        
    - name: Archive mapping.txt
      uses: actions/upload-artifact@v3
      with:
        name: Mappings
        path: build/tmp/proguard/mapping.txt
